name: C/C++ CI

on:
  push:
    branches: [ "MiSTer-v5.15" ]
  pull_request:
    branches: [ "MiSTer-v5.15" ]

jobs:
  build:
    env: 
      ARCH: "arm"
      LOCALVERSION: "MiSTer"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: wget
      run: wget -c https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz && cat gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz | tar xJ
      env: 
        CROSS_COMPILE: "$GITHUB_WORKSPACE/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-"
    - name: make
      run: make -j3 zImage
    - name: make
      run: make arch/arm/boot/dts/socfpga_cyclone5_de10_nano.dtb
    - name: zImage
      run: cat arch/arm/boot/zImage arch/arm/boot/dts/socfpga_cyclone5_de10_nano.dtb > zImage_dtb
