name: C/C++ CI

on:
  push:
    branches: [ "MiSTer-v5.15" ]
  pull_request:
    branches: [ "MiSTer-v5.15" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt-get
      run: sudo apt-get install build-essential git libncurses-dev flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf liblz4-tool bc curl gcc git libssl-dev libncurses5-dev lzop make u-boot-tools libgmp3-dev libmpc-dev -y
    - name: wget
      run: wget -c https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz && cat gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz | tar xJ
    - name: make
      run: make ARCH=arm EXTRAVERSION=-MiSTer CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf- -j6 zImage
    - name: make
      run: make ARCH=arm EXTRAVERSION=-MiSTer CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf- socfpga_cyclone5_de10_nano.dtb
    - name: zImage
      run: cat $GITHUB_WORKSPACE/arch/arm/boot/zImage $GITHUB_WORKSPACE/arch/arm/boot/dts/socfpga_cyclone5_de10_nano.dtb > $GITHUB_WORKSPACE/zImage_dtb
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: zImage_dtb
        path: zImage_dtb
